server:
  port: 8084
  accessTokenTimeOut: 1800
  refreshTokenTimeOut: 2400
spring:
  profiles:
    active: dev
  application:
    name: cloud-provider-auth
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: 123456
      # 初始化大小，最大，最小
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 20
      # 配置间隔多久才能进行一次检查，检查需要关闭的连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  redis:
    database: 0
    host: 192.168.147.132
    port: 6389
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 1000
        # 控制一个pool最多有多少个状态为idle(空闲的)的jedis实例
        max-idle: 100
        # 控制一个pool最少有多少个状态为idle(空闲的)的jedis实例
        min-idle: 0
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
      shutdown-timeout: 10000
    timeout: 300
    sentinel:
      master: mymaster
      nodes: 192.168.147.132:26379,192.168.147.132:26389,192.168.147.132:26399
feign:
  hystrix:
    enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.com.nanfeng.cloud.model.po

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

security:
  oauth2:
    resource:
      user-info-uri: http://127.0.0.1:8084/user
      prefer-token-info: false
      service-id: cloud-gateway
    client:
      client-id: nanfeng
      client-secret: nanfengbujing
      scope: "*"